# Generated by Django 4.1.3 on 2022-11-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatresponse',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
